### ISSUE TITLE
github全自动同步上游

### ISSUE THREAD

**Issue by jimodeniuren** [jimodeniuren/blog#19]
[picgo]: # 'https://cdn.jsdelivr.net/gh/jimodeniuren/tuchuang//0072Vf1pgy1foxlhvnh9qj31hc0u0tmu.jpg'

# github全自动同步上游

## 起因

自从知道了github的action有多好用之后，在github上面找了好多薅github羊毛的action项目，薅的爽到不行，这些项目的作者大多也都非常勤奋，每天都有更新，这样就带来了一个问题，也就是要经常去手动创建pull，实在是太麻烦了，于是我就想着有没有全自动同步的工具可以解决这样的一个问题。

## 安装github pull

[安装地址](https://github.com/apps/pull)

安装的时候选择自己想要自动同步的仓库，如图中所示我选择了四个想要同步的仓库，然后安装。

![](https://cdn.jsdelivr.net/gh/jimodeniuren/tuchuang/selectrepositories.jpg)

这个应用是github上一个大佬写的应用，被github官方收录了，安装好之后会每三小时自动检查你设置好的想要同步上游的仓库，看上游有没有新的commit，如果有的话就会自动帮你merge，非常方便。

## 使用

理论上来讲通过上面的安装之后所有的仓库都会自动的进行同步，但是是强制同步，也就是说你的仓库会严格的与原作者一模一样，但是很多时候我们都想要在仓库中保留一些自己的个性化的设置，这样的话强制同步就不太好了，所以我们可以在仓库/.github文件夹下创建一个pull.yml的配置文件，这个文件在自动pull的时候会被优先读取，如果有的话就会根据上面的配置来pull，pull.yml的内容如下：

```yaml
version: "1"
rules:                         # Array of rules
  - base: 你的仓库的分支               # Required. Target branch
    upstream: 作者名:作者仓库的分支    # Required. Must be in the same fork network.
    mergeMethod: merge     # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: true        # Optional, merge pull request even when the mergeable_state is not clean. Default: false
```

添加好之后需要激活一下，访问

https://pull.git.ci/check/你的github名/仓库名

这个网址，如果能正常打开的话就说明配置生效了！

## 后记

终于从无止尽的merge地狱中解脱出来了！
